### ISSUE TITLE
Warn: The slice struct is just a wrapper around a raw pointer

### ISSUE THREAD

**Issue by lokax** [WangTingZheng/Paperdb#4]
Don't pass a stack object's pointer to the constructor of `Slice` that will be returned. Because this is undefined behavior.
And the `Slice` copy constructor just copies the pointer.
Two Solution:
1、add a new input paramter.
2、we can just return a string. It will call move constructor function.

**Comment by lokax** [comment]
#3

**Comment by WangTingZheng** [comment]
The function [GetLengthPrefixedSlice](https://github.com/WangTingZheng/Paperdb/blob/ff040d4a7b37e5f80c16b365f548df774e7afb32/util/coding.cc#L145leveldb) in LevelDB Pass Slice's pointer too, and this function works well.
```c++
bool GetLengthPrefixedSlice(Slice* input, Slice* result) {
  uint32_t len;
  if (GetVarint32(input, &len) && input->size() >= len) {
    *result = Slice(input->data(), len);
    input->remove_prefix(len);
    return true;
  } else {
    return false;
  }
}
```
